import 'package:flutter/material.dart';
class EducationScreen extends StatefulWidget {
  @override
  _EducationScreenState createState() => _EducationScreenState();
}

class _EducationScreenState extends State<EducationScreen> {
  TextEditingController editingController = TextEditingController();
  final duplicateItems = Listeler().duplicateItems;

  var items = List<String>();

  @override
  void initState() {
    items.addAll(duplicateItems);
    super.initState();
  }

  void filterSearchResults(String query) {
    List<String> dummySearchList = List<String>();
    dummySearchList.addAll(duplicateItems);
    if (query.isNotEmpty) {
      List<String> dummyListData = List<String>();
      dummySearchList.forEach((item) {
        if (item.contains(query.toUpperCase()) ||
            item.contains(query.toLowerCase())) {
          dummyListData.add(item);
        }
      });
      setState(() {
        items.clear();
        items.addAll(dummyListData);
      });
      return;
    } else {
      setState(() {
        items.clear();
        items.addAll(duplicateItems);
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        children: [
          SizedBox(height: 10),
          Padding(
            padding: const EdgeInsets.all(10.0),
            child: TextField(
              textCapitalization: TextCapitalization.characters,
              onChanged: (value) {
                filterSearchResults(value);
              },
              controller: editingController,
              decoration: InputDecoration(
                labelText: "Ara",
                hintText: "İsim Soyisim",
                prefixIcon: Icon(Icons.search),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.all(
                    Radius.circular(10.0),
                  ),
                ),
              ),
            ),
          ),
          SizedBox(height: 10),
          Expanded(
            child: ListView.builder(
              itemCount: items.length,
              itemBuilder: (context, index) {
                return Card(
                  child: ListTile(onTap: () {
                    print(items[index]);
                  },
                    //leading: Icon(Icons.person),
                    //trailing: Icon(Icons.menu),
                    subtitle: Text(
                        'TC NO'),
                    dense: true,
                    title: Text(items[index]),
                  ),
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}
class Listeler{
  final duplicateItems = ['A.ÇETİN ERASLAN',
    'ABDULKADİR SAGDİÇ',
    'ABDURRAHMAN BULUT',
    'ABDURRAHMAN GÖKDAŞ',
    'ABİDİN BİÇEN',
    'ABİDİN KILIÇARSLAN',
    'ADEM ÖZCAN',
    'AHMET BABAYİĞİT',
    'AHMET CAYGIN',
    'samet ulutürk',
    'AHMET ÇİFTÇİ',
    'AHMET DEMİR',
    'AHMET DİŞLİOĞLU',
    'AHMET EKİCİ',
    'AHMET İLHAN',
    'AHMET KAYA',
    'AHMET KESİCİ',
    'AHMET SORGUNLU',
    'AHMET ŞAHİN',
    'AHMET UÇAR',
    'AHMET ULUTAŞ',
    'ALİ CANBOLAT',
    'ALİ CANDEMİR',
    'ALİ ÇETİNYÜREK',
    'ALİ İNAN',
    'ALİ KILIÇASLAN',
    'ALİ OSMAN KALKAN',
    'ALİ ŞAHİN',
    'ALİ ŞİMŞEK',
    'ALİ YAMAN',
    'ARİF BİÇEN',
    'ATALAY DURANDEMİR',
    'AYHAN SEYRAN',
    'AZİZ ERSOY',
    'AZMİ OCAK',
    'AZMİ TUNÇEL',
    'BAKİ EKİCİ',
    'BATTAL BULUT',
    'BAYRAM DUYAN',
    'BEKİR AKDOĞDU',
    'BEKİR ŞAHİN',
    'BEKİR ŞIVGIN',
    'BEKİR TUNCAL',
    'BİLAL YILDIZ',
    'BİROL GÜRLER',
    'BÜNYAMİ AKDOĞAN',
    'CAFER KOÇER',
    'CELAL YILDIRIM',
    'CEMALETTİN ARSLAN',
    'CEMALETTİN KILIÇ',
    'CENGİZ DERE',
    'CENGİZ SAFTAN',
    'CENGİZ YİĞİT',
    'CUMA İNAN',
    'DAVUT GÜLBAHÇE',
    'DERVİŞ MİLLET',
    'DOĞAN KOÇAKER',
    'DURDU BİÇER',
    'DURMUŞ TUFAN',
    'DÜRÜYE ÇAMSU ÖZBEK',
    'EFKAN ZEKİ',
    'EKREM SEYRAN',
    'ELİF ERTEN',
    'EMRULLAH BATUR',
    'ERDAL AÇIKGÖZ',
    'ERDAL ATALAY',
    'ERDAL AYDOĞAN',
    'ERDAL KALE',
    'ERDAL ÜNSAL',
    'EROL TORAMAN',
    'EYÜP AKGÜN',
    'EYÜP BİÇEN',
    'FAHRİ BOLAT',
    'FAİK ERDEN',
    'FAİK GEDİK',
    'FATİH KARA',
    'FATİH MEHMET AKSES',
    'FEHMİ ÇELİK',
    'FİKRET KARAASLAN',
    'GAZİ SARIASLAN',
    'H. BAYRAM MURAT',
    'H. MURAT DÜZGÜN',
    'HACI RUHİ BACANLI',
    'HADİ ALTUNBEK',
    'HAKAN KOÇAK',
    'HALİL BACANAK',
    'HALİL COŞAR',
    'HAMDİ PEKDEMİR',
    'HAMZA ARSLAN',
    'HAMZA YILDIZ',
    'HARUN ŞAHİN',
    'HASAN OĞUZHAN',
    'HAŞMET SATICI',
    'HATİCE UYGUR',
    'HAYDAR ÖZKAN',
    'HAYDAR SELVİ',
    'HİDAYET CINAKLI',
    'HULUSİ DEMİR',
    'HÜSEYİN DOĞRUTEKİN',
    'HÜSEYİN EREN',
    'HÜSEYİN ERSİN',
    'HÜSEYİN KOKGİL',
    'HÜSEYİN NAZLI',
    'İBRAHİM KAYIM',
    'İBRAHİM ÜNAL',
    'İHSAN DALGIÇ',
    'İLYAS KALA',
    'İLYAS KAYA',
    'İSKENDER SOLMAZ',
    'İSMAİL ERDİNÇ',
    'İSMAİL KILIÇ',
    'İSMET CANDEMİR',
    'KADİR KAYADİBİ',
    'KAMİL ERDOĞAN',
    'KAZIM ALPASLAN',
    'KAZIM AYDEMİR',
    'KERAMETTİN BACANLI',
    'KORHAN ŞENOL',
    'KÖKSAL SARIASLAN',
    'MACİT ARSLAN',
    'MACİT YAZAN',
    'MAHMUT ALTINOK',
    'MAHMUT BATUR',
    'MAHMUT GÜVEN',
    'MAHMUT ŞEVKET YILDIZOĞLU',
    'MEHMET ALİ ERGÜL',
    'MEHMET BARAN',
    'MEHMET ÇİÇEK',
    'MEHMET ÇİTÇİ',
    'MEHMET DURAK',
    'MEHMET ERCAN',
    'MEHMET GÖK',
    'MEHMET KILIÇ',
    'MEHMET ÖZTÜRK',
    'MEHMET ÖZÜDOĞRU',
    'MEHMET SEYFİ',
    'MEHMET TAŞDAN',
    'MEHMET TURGUT',
    'MEHMET VAHDETTİN DEMİRCAN',
    'MEHTAP KOÇAK',
    'MELEK ÖZKAN',
    'MESUT ATALAY',
    'MEVLUŞ ÜNAL',
    'MİKAİL YILDIRIM',
    'MİKDAT UÇAR',
    'MUAMMER KILIÇ',
    'MURAT GÜNDOĞDU',
    'MURAT KARTAL',
    'MURAT ÖZDÖL',
    'MURAT ÖZER',
    'MURAT SATILMIŞ',
    'MURAT ZEKİ',
    'MUSA DOĞAN',
    'MUSTAFA BAĞCI',
    'MUSTAFA ÇETİN',
    'MUSTAFA KAYA.',
    'MUSTAFA KOÇAK',
    'MUSTAFA NAZLI',
    'MUSTAFA ŞİMŞEK',
    'MUSTAFA YOZGATLI',
    'MUTEBER KARAMEŞE',
    'NAİL ÖZSOY',
    'NAZMİ BÖLÜKBAŞI',
    'NEBİ EKİNCİ',
    'NECATİ ŞAHİN',
    'NECATİ YILMAZ',
    'NECDET ALTUNOK',
    'NECİP ÇINAR',
    'NECİP TETİK',
    'NEVZAT GÜNGÖRMEZ',
    'NİHAT DURAN',
    'NİHAT ŞAHİN',
    'NİHAT ÜSTÜNTAŞ',
    'NİYAZİ KOÇSOY',
    'NUMAN TAŞER',
    'NURİ ERBAŞ',
    'NUSRET ALPER',
    'NUSURAT AKGÜN',
    'O. NURİ YILMAZ',
    'OSMAN BAŞAK',
    'OSMAN ÇALIŞKAN',
    'OSMAN KILIÇAY',
    'OSMAN KOŞAR',
    'OSMAN LAFCI',
    'OSMAN NURİ TOKATLIOĞLI',
    'ÖMER GÜRAN',
    'ÖMER KARABULUT',
    'PERVİN KORKMAZ',
    'RAHMİ ÖZDEMİR',
    'RAMAZAN ÜZÜMVEREN',
    'RAŞİT COŞGUN',
    'RECEP BİLGİN',
    'RIZA GÜLAY',
    'SABRİ SEYRAN',
    'SADETTİN KILINÇASLAN',
    'SAİT ŞENÖZ',
    'SALİH ÇELİK',
    'SALİH ERASLAN',
    'SALİH METE',
    'SALİH ŞAHİN',
    'SAMİ AYDIN',
    'SATILMIŞ ELMALI',
    'SATILMIŞ SÜMER',
    'SAVAŞ OCAK',
    'SEMAHAT SEYRAN ERSALMAN',
    'SEYİT KURT',
    'SEZAİ BAYINDIR',
    'SİNAN ÜNAL',
    'ŞABAN AVCI',
    'ŞABAN KILIÇ',
    'ŞAHABETTİN SEVİNÇ',
    'ŞEVKET EYMİR',
    'ŞEVKET SARGIN',
    'ŞEVKİ KARABULUT',
    'TAHİR ASLAN',
    'TAHSİN AYGAR',
    'TATLI GAZEL',
    'TEVFİK AVCI',
    'TUNCAY TOKATLIOĞLU',
    'TURGAY KAYA',
    'UĞUR KOÇAK',
    'ÜMİT ARSLAN',
    'ÜNSAL ADIGÜZEL',
    'ÜZEYİR ŞENÖZ',
    'VASIF AKCİN',
    'VEDAT YORULMAZ',
    'VELİ KILIÇ',
    'VEYSEL DOĞAN',
    'VEYSEL ŞAHİN',
    'VURAL ALTUN',
    'YAHYA KOÇAK',
    'YAKUP GÜNEŞ',
    'YAKUP ÖZCAN',
    'YALÇIN BİLDİM',
    'YAŞAR ARKAÇ',
    'YAŞAR GÜLER',
    'YAŞAR GÜRER',
    'YAŞAR SEYRAN',
    'YAŞAR YIKILMAZ',
    'YAŞAR YİĞİT',
    'YUSUF EVCİMEN',
    'YUSUF TEMUR',
    'YUSUF ZİYA KARACA',
    'ZAMİR USLU',
    'ZEKERİYA KAYA',
    'ZEKİ ÜSTÜNTAŞ',
    'ALİ ŞİMŞEK',
    'KERAMETTİN BACANLI',
    'KÖKSAL SARIASLAN',
    'NAİL ÖZSOY',
    'ERDAL ÜNSAL',
    'MEHMET ÖZTÜRK',
    'DURDU BİÇER',
    'DURAK ULAK',
    'HAMDİ PEKDEMİR',
    'MUSTAFA ŞİMŞEK',
    'MESUT ATALAY',
    'RIZA GÜLAY',
    'ALİ CANDEMİR',
    'MUSA DOĞAN',
    'ALİ YAMAN',
    'ABİDİN BİÇEN',
    'DERVİŞ MİLLET',
    'İLYAS KAYA',
    'ŞEVKİ KARABULUT',
    'HAYDAR SELVİ',
    'A.ÇETİN ERASLAN',
    'OSMAN KOŞAR',
    'OSMAN ÇALIŞKAN',
    'ZEKİ ÜSTÜNTAŞ',
    'TURGAY KAYA',
    'VURAL ALTUN',
    'HARUN ŞAHİN',
    'O. NURİ YILMAZ',
    'MİKDAT UÇAR',
    'NEVZAT GÜNGÖRMEZ',
    'YAHYA KOÇAK',
    'SAİT ŞENÖZ',
    'H. MURAT DÜZGÜN',
    'BEKİR AKDOĞDU',
    'EYÜP BİÇEN',
    'NECATİ ŞAHİN',
    'TATLI GAZEL',
    'ERDAL ATALAY',
    'ALİ ÇETİNYÜREK',
    'ALİ ŞAHİN',
    'MEHMET KILIÇ',
    'MUSTAFA ÇETİN',
    'YUSUF TEMUR',
    'KAMİL ERDOĞAN',
    'MACİT YAZAN',
    'NECATİ YILMAZ',
    'RAMAZAN ÜZÜMVEREN',
    'SATILMIŞ SÜMER',
    'PERVİN KORKMAZ',
    'SADETTİN KILINÇASLAN',
    'ABİDİN KILIÇARSLAN',
    'CENGİZ SAFTAN',
    'HATİCE UYGUR',
    'BEKİR TUNCAL',
    'ELİF ERTEN',
    'HALİL COŞAR',
    'İSMET CANDEMİR',
    'KORHAN ŞENOL',
    'MELEK ÖZKAN',
    'MEVLUŞ ÜNAL',
    'MUSTAFA KOÇAK',
    'MUTEBER KARAMEŞE',
    'OSMAN NURİ TOKATLIOĞLI',
    'SİNAN ÜNAL',
    'FATİH KARA',
    'UĞUR KOÇAK',
    'BİROL GÜRLER',
    'MEHMET GÖK',
    'SEMAHAT SEYRAN ERSALMAN',
    'MEHMET ALİ ERGÜL',
    'NUSRET ALPER',
    'İHSAN DALGIÇ',
    'MACİT ARSLAN',
    'MAHMUT ŞEVKET YILDIZOĞLU',
    'VELİ KILIÇ',
    'YAKUP ÖZCAN',
    'ABDURRAHMAN BULUT',
    'ABDURRAHMAN GÖKDAŞ',
    'AHMET1 KAYA1',
    'FATİH MEHMET AKSES',
    'H. BAYRAM MURAT',
    'MEHMET SEYFİ',
    'ÜMİT ARSLAN',
    'ABDULKADİR SAGDİÇ',
    'AHMET DEMİR',
    'ALİ KILIÇASLAN',
    'BAKİ EKİCİ',
    'CENGİZ DERE',
    'CUMA İNAN',
    'DURMUŞ TUFAN',
    'DÜRÜYE ÇAMSU ÖZBEK',
    'ERDAL KALE',
    'FAİK GEDİK',
    'GAZİ SARIASLAN',
    'HAMZA23 YILDIZ2',
    'HÜSEYİN ERSİN',
    'MEHMET ÖZÜDOĞRU',
    'MEHMET ÇİTÇİ',
    'MEHTAP KOÇAK',
    'MURAT KARTAL',
    'MUSTAFA KAYA.',
    'NİHAT DURAN',
    'NİHAT ŞAHİN',
    'SABRİ SEYRAN',
    'SALİH ERASLAN',
    'ADEM ÖZCAN',
    'CENGİZ YİĞİT',
    'KAZIM ALPASLAN',
    'MURAT ÖZDÖL',
    'AHMET UÇAR',
    'CELAL YILDIRIM',
    'DAVUT GÜLBAHÇE',
    'HİDAYET CINAKLI',
    'MUSTAFA NAZLI',
    'NİYAZİ KOÇSOY',
    'AHMET CAYGIN',
    'ALİ CANBOLAT',
    'ARİF BİÇEN',
    'EKREM SEYRAN',
    'FİKRET KARAASLAN',
    'HACI RUHİ BACANLI',
    'HÜSEYİN EREN',
    'HÜSEYİN KOKGİL',
    'İBRAHİM ÜNAL',
    'MUSTAFA YOZGATLI',
    'OSMAN LAFCI',
    'RAŞİT COŞGUN',
    'ŞABAN KILIÇ',
    'TAHİR ASLAN',
    'HAKAN KOÇAK',
    'MİKAİL YILDIRIM',
    'EFKAN ZEKİ',
    'MUAMMER KILIÇ',
    'VASIF AKCİN',
    'AHMET EKİCİ',
    'AHMET SORGUNLU',
    'AHMET İLHAN',
    'AHMET KESİCİ',
    'AHMET ÇALIŞKAN',
    'AHMET BABAYİĞİT',
    'ALİ OSMAN KALKAN',
    'AYHAN SEYRAN',
    'AZMİ TUNÇEL',
    'AZMİ OCAK',
    'BATTAL BULUT',
    'BAYRAM DUYAN',
    'BEKİR ZEYNİOĞLU',
    'BİLAL YILDIZ',
    'BÜNYAMİ AKDOĞAN',
    'CAFER KOÇER',
    'CEMALETTİN KILIÇ',
    'CEMALETTİN ARSLAN',
    'DOĞAN KOÇAKER',
    'EMRULLAH BATUR',
    'ERDAL AYDOĞAN',
    'EROL TORAMAN',
    'EYÜP AKGÜN',
    'FAİK ERDEN',
    'FEHMİ ÇELİK',
    'HALİL BACANAK',
    'HAMZA ARSLAN',
    'HASAN OĞUZHAN',
    'HAŞMET SATICI',
    'HAYDAR ÖZKAN',
    'HULUSİ DEMİR',
    'HÜSEYİN DOĞRUTEKİN',
    'HÜSEYİN NAZLI',
    'İBRAHİM KAYIM',
    'İLYAS KALA',
    'İSKENDER SOLMAZ',
    'İSMAİL ERDİNÇ',
    'İSMAİL KILIÇ',
    'KAZIM AYDEMİR',
    'MAHMUT BATUR',
    'MAHMUT GÜVEN',
    'MEHMET TAŞDAN',
    'MEHMET ERCAN',
    'MEHMET DURAK',
    'MEHMET VAHDETTİN DEMİRCAN',
    'MURAT SATILMIŞ',
    'MURAT GÜNDOĞDU',
    'MURAT ZEKİ',
    'MUSTAFA BAĞCI',
    'NAZMİ BÖLÜKBAŞI',
    'NEBİ EKİNCİ',
    'NECDET ALTUNOK',
    'NECİP TETİK',
    'NİHAT ÜSTÜNTAŞ',
    'NURİ ERBAŞ',
    'NUSURAT AKGÜN',
    'RAHMİ ÖZDEMİR',
    'RECEP BİLGİN',
    'SALİH ŞAHİN',
    'SALİH METE',
    'SATILMIŞ ELMALI',
    'SAVAŞ OCAK',
    'SEZAİ BAYINDIR',
    'ŞABAN AVCI',
    'ŞEVKET EYMİR',
    'ŞEVKET SARGIN',
    'TEVFİK AVCI',
    'TUNCAY TOKATLIOĞLU',
    'VEDAT YORULMAZ',
    'YAKUP GÜNEŞ',
    'YALÇIN BİLDİM',
    'YAŞAR YIKILMAZ',
    'YAŞAR GÜLER',
    'YAŞAR GÜRER',
    'YAŞAR ARKAÇ',
    'YAŞAR YİĞİT',
    'YUSUF EVCİMEN',
    'YUSUF ZİYA KARACA',
    'ZEKERİYA KAYA',
    'VEYSEL DOĞAN',
    'ALİ İNAN',
    'ATALAY DURANDEMİR',
    'ERDAL AÇIKGÖZ',
    'HADİ ALTUNBEK',
    'MEHMET TURGUT',
    'NECİP ÇINAR',
    'ŞAHABETTİN SEVİNÇ',
    'ÜZEYİR ŞENÖZ',
    'AHMET ÇİFTÇİ',
    'AHMET DİŞLİOĞLU',
    'AHMET ŞAHİN',
    'ALİ DUYAN',
    'AZİZ ERSOY',
    'ÖMER GÜRAN',
    'SEYİT KURT',
    'YAŞAR SEYRAN',
    'ZAMİR USLU',
    'SALİH ÇELİK',
    'AHMET ULUTAŞ',
    'MAHMUT ALTINOK',
    'NUMAN TAŞER',
    'VEYSEL ŞAHİN',
    'YAŞAR YİĞİT',
    'BEKİR ŞAHİN',
    'BEKİR ŞIVGIN',
    'FAHRİ BOLAT',
    'KADİR KAYADİBİ',
    'MURAT ÖZER',
    'OSMAN BAŞAK',
    'OSMAN KILIÇAY',
    'ÖMER KARABULUT',
    'SAMİ AYDIN',
    'TAHSİN AYGAR',
    'MEHMET ÇİÇEK',
    'ÜNSAL ADIGÜZEL',
    'MUSTAFA ERŞEN',
    'TEST2 TEST3',
    'samet samet',
    'ğğğ ğğğğ',
    'özlem özkaya',
    'test test 66',
    'samet sssss',
    'SAMET ULUTÜRK',
    'filiz murat',
  ];
}